before_script:
  - export MAKEFLAGS="-j2"

test: &test
  image: sagemath/sagemath-develop
  script:
    - sage -c "print(\"hello\")"
    - sage -pip install .
    - export SURFACE_DYNAMICS_PATH="$(pwd)"
    - export SURFACE_DYNAMICS_INSTALL="$(sage -c 'import surface_dynamics; print(surface_dynamics.__path__[0])')"
    - cd
    - sage -t --force-lib --long ${SURFACE_DYNAMICS_INSTALL}
    - cp ${SURFACE_DYNAMICS_PATH}/README README.rst
    - sage -t --force-lib --long README.rst

test:8.7:
  << : *test
  image: sagemath/sagemath-dev:8.7

test:8.6:
  << : *test
  image: sagemath/sagemath-dev:8.6

test:8.5:
  << : *test
  image: sagemath/sagemath-dev:8.5
