before_script:
  - export MAKEFLAGS="-j2"

test: &test
  image: sagemath/sagemath-develop
  script:
    - sage -c "print(\"hello\")"
    - sage -pip install .
    - export SURFACE_DYNAMICS_PATH="$(sage -c 'import surface_dynamics; print(surface_dynamics.__path__[0])')"
    - cd
    - sage -t --force-lib --long ${SURFACE_DYNAMICS_PATH}
    - cp README README.rst
    - sage -t README.rst
    - cd doc/
    - make html

test:8.7:
  << : *test
  image: sagemath/sagemath-dev:8.7

# deactivated for now... see https://gitlab.com/videlec/surface_dynamics/issues/5
#
# test:8.6:
#  << : *test
#  image: sagemath/sagemath-dev:8.6
#
# test:8.5:
#  << : *test
#  image: sagemath/sagemath-dev:8.5
