before_script:
  - export MAKEFLAGS="-j2"

test:dev: &test
  image: sagemath/sagemath-dev:develop
  script:
    - sage -c 'import sage.env; print(sage.env.SAGE_VERSION)'
    - sage -pip install .
    - export SURFACE_DYNAMICS_PATH="$(pwd)"
    - export SURFACE_DYNAMICS_INSTALL="$(sage -c 'import surface_dynamics; print(surface_dynamics.__path__[0])')"
    - cd
    - sage -t --force-lib --long ${SURFACE_DYNAMICS_INSTALL}
    - sage -i gap_packages
    - sage -i latte_int
    - sage -t --force-lib --long ${SURFACE_DYNAMICS_INSTALL}
    - cp ${SURFACE_DYNAMICS_PATH}/README README.rst
    - sage -t --force-lib --long README.rst

test:9.0:
  << : *test
  image: sagemath/sagemath-dev:9.0

# NOTE: 8.9-dev image is absent or misconfigured in docker hub...
# We just disable it for now
#test:8.9:
#  << : *test
#  image: sagemath/sagemath-dev:8.9

test:8.8:
  << : *test
  image: sagemath/sagemath-dev:8.8

test:8.7:
  << : *test
  image: sagemath/sagemath-dev:8.7

test:8.6:
  << : *test
  image: sagemath/sagemath-dev:8.6
