image: ubuntu:18.04
before_script:
- export DEBIAN_FRONTEND=noninteractive   # avoid tzdata interactive configuration
- apt-get -qq update
- apt-get install wget
- wget http://mirrors.mit.edu/sage/linux/32bit/sage-8.7-Ubuntu_18.04-i686.tar.bz2
- tar xzf sage-8.7-Ubuntu_18.04-i686.tar.bz2
- cd SageMath
- ./sage -c "print(hello)"
- ./sage -pip install ../
- export SURFACE_DYNAMICS_PATH="$(sage -c 'import surface_dynamics; print(surface_dynamics.__path__[0])')"

python2.7:
  script:
    - sage -t --force-lib --long ${SURFACE_DYNAMICS_PATH}
    - cp README README.rst
    - sage -t README.rst
    - cd doc/
    - make html
