dist: trusty
sudo: required
language: c
cache:
  ccache: true
  timeout: 1000
env:
  - SAGE_VERSION="8.0"
  - SAGE_VERSION="8.1"
  - SAGE_VERSION="8.2"
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install gcc g++ gfortran
install: 
  - export SAGE_MIRROR="http://mirrors.mit.edu/sage/linux/64bit"
  - export SAGE_BINARY="sage-${SAGE_VERSION}-Ubuntu_14.04-x86_64.tar.bz2"
  - export SAGE="${HOME}/SageMath/sage"
  - ./.travis_sage_install.sh
  - ${SAGE} --version
  - which gcc
  - ${SAGE} -sh -c "which gcc"
  - ccache -s
  - ${SAGE} -pip install --verbose --no-index --user .
  - export SURFACE_DYNAMICS_PATH="$(${SAGE} -c 'import surface_dynamics; print(surface_dynamics.__path__[0])')"
script:
  - ${SAGE} -t --force-lib --long ${SURFACE_DYNAMICS_PATH}
  - cp README README.rst
  - ${SAGE} -t README.rst
  - cd doc/
  - ${SAGE} -sh -c "make html"
