dist: trusty
sudo: required
language: c
cache:
  ccache: true
  directories:
  - ${HOME}/SageMath
  timeout: 1000
env:
  SAGE_MIRROR="http://mirrors.mit.edu/sage/linux/64bit"
  SAGE_BINARY="sage-8.0-Ubuntu_14.04-x86_64.tar.bz2"
  SAGE="${HOME}/SageMath/sage"
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install gcc g++ gfortran
# command to install dependencies
install: 
  - ./.travis_sage_install.sh
  - ${SAGE} --version
  - which gcc
  - ${SAGE} -sh -c "which gcc"
  - ${SAGE} -pip install --verbose --no-index --user .
# command to run tests
script:
  - ${SAGE} -t --force-lib --long surface_dynamics/
  - cd doc/
  - ${SAGE} -sh -c "make html"
