# This file lists the minimal dependencies needed to build the documentation
# for surface-dynamics. Create a conda environment with these dependencies
# preinstalled with:
# conda env create -n surface-dynamics-docbuild -f ../environment.yml
# conda env update -n surface-dynamics-docbuild -f environment.yml
name: surface-dynamics-docbuild
channels:
  - conda-forge
dependencies:
  - sphinx
  - jupyter_sphinx
  - jupytext
  - myst-nb
  # Force a recent furo to work around CSS errors
  - furo=2024.8.6
  - linkchecker
  - sphinx_rtd_theme
  - pip
  - pip:
    - sage-docbuild==10.3
